import { describe, expect, it } from "vitest";

import { hashPassword, verifyPassword } from "./password";

describe("hashPassword / verifyPassword — real scrypt round trip", () => {
  it("a real hash generated by hashPassword verifies successfully with the same password", async () => {
    const hash = await hashPassword("correct horse battery staple");
    await expect(verifyPassword("correct horse battery staple", hash)).resolves.toBe(true);
  });

  it("a different password does not verify against the real hash", async () => {
    const hash = await hashPassword("correct horse battery staple");
    await expect(verifyPassword("wrong password", hash)).resolves.toBe(false);
  });

  it("produces a different salt (and therefore a different hash string) for the same password on each call", async () => {
    const first = await hashPassword("same-password");
    const second = await hashPassword("same-password");
    expect(first).not.toBe(second);
    // Both must still independently verify against the same password.
    await expect(verifyPassword("same-password", first)).resolves.toBe(true);
    await expect(verifyPassword("same-password", second)).resolves.toBe(true);
  });
});

describe("verifyPassword — malformed stored hash never throws", () => {
  it("a hash with no ':' separator returns false", async () => {
    await expect(verifyPassword("anything", "not-a-valid-hash-at-all")).resolves.toBe(false);
  });

  it("an empty stored hash returns false", async () => {
    await expect(verifyPassword("anything", "")).resolves.toBe(false);
  });

  it("a hash missing the key half (trailing colon) returns false", async () => {
    await expect(verifyPassword("anything", "somesalt:")).resolves.toBe(false);
  });

  it("a hash missing the salt half (leading colon) returns false", async () => {
    await expect(verifyPassword("anything", ":somekey")).resolves.toBe(false);
  });

  it("a key that decodes to zero bytes of invalid hex returns false, not a false-positive match", async () => {
    // "zz" contains no valid hex digits, so Buffer.from(key, "hex") silently
    // truncates to an empty buffer rather than throwing. Without a guard,
    // scrypt would then be asked to derive a 0-length key, and comparing
    // two empty buffers trivially "matches" regardless of the password —
    // this is the exact corrupt-data scenario this test locks in as
    // rejected, not accepted.
    await expect(verifyPassword("any-password-at-all", "somesalt:zz")).resolves.toBe(false);
  });

  it("a key with a partially-invalid hex tail (truncated decode) returns false", async () => {
    // "ab##" decodes only the leading "ab" pair (1 byte) before stopping at
    // the invalid characters — a shorter buffer than the key string implies.
    await expect(verifyPassword("any-password-at-all", "somesalt:ab##")).resolves.toBe(false);
  });

  it("a syntactically valid but short stored key does not throw and does not falsely verify", async () => {
    // "ab" is valid hex (1 byte) — far shorter than a real KEY_LENGTH=64
    // stored key, but syntactically well-formed. This must not throw, and
    // for an unrelated password there is no realistic way it verifies true.
    await expect(verifyPassword("any-password-at-all", "somesalt:ab")).resolves.toBe(false);
  });
});

describe("verifyPassword — empty/whitespace password inputs never throw", () => {
  it("an empty password against a real hash does not throw and does not verify", async () => {
    const hash = await hashPassword("real-password");
    await expect(verifyPassword("", hash)).resolves.toBe(false);
  });

  it("a whitespace-only password against a real hash does not throw and does not verify", async () => {
    const hash = await hashPassword("real-password");
    await expect(verifyPassword("   ", hash)).resolves.toBe(false);
  });

  it("hashing an empty password still produces a hash that verifies against that same empty password", async () => {
    // hashPassword has no minimum-length contract of its own — that's
    // enforced upstream by validation schemas — so this only pins down
    // that the primitive itself doesn't special-case or crash on "".
    const hash = await hashPassword("");
    await expect(verifyPassword("", hash)).resolves.toBe(true);
    await expect(verifyPassword("not-empty", hash)).resolves.toBe(false);
  });
});
